name: CraneStack
options:
  bundleIdPrefix: com.austinmcrane
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

packages:
  CraneKit:
    path: ../../cranekit

targets:
  CraneStack:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: CraneStack
    dependencies:
      - package: CraneKit
        product: CraneKit
      - package: CraneKit
        product: CraneKitUI
    info:
      path: CraneStack/Info.plist
      properties:
        UILaunchScreen:
          UIColorName: ""
        CFBundleDisplayName: CraneStack
    entitlements:
      path: CraneStack/CraneStack.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.austinmcrane.cranestack
        SWIFT_VERSION: "5.0"
        DEVELOPMENT_TEAM: ""
